### ISSUE TITLE
TransactionProfile.xsd - Revision History Typo

### ISSUE THREAD

**Issue by andreb1972** [MESAInternational/B2MML-BatchML#15] opened 2019-02-04 04:06 UTC
Typo:
Revision History:  "Added new objects from Part 4 and Part 4" should probably be "Added new objects from Part 2 and Part 4"

**Comment by Dennis-Brandl** [comment] 2019-02-05 19:37
Yes,looks like a type, should be corrected.

**Comment by Dennis-Brandl** [comment] 2020-01-27 18:55
Corrected in January 2020 Sprint

**Comment by JoeDo** [comment] 2020-02-03 18:35
Confirmed that the change has been made in the January-2020-Sprint branch. I'll circle back and Close this issue after the changes have been merged into Master.

**Comment by Dennis-Brandl** [comment] 2020-08-13 20:46
Revision history removed, everything to be gin GitHub. Issue closed.

**Closed by Dennis-Brandl** 2020-08-13 20:46 UTC
